config/routes.rb
Rails.application.routes.draw do
  get "static_pages/about"

  resources :articles, only: [:index, :show] do
    resources :comments
  end

  namespace :admin do
    get '/', action: :index, controller: 'dashboard'
    resources :articles, :comments
  end

  resources :about
  resources :notifications

  root "articles#index"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }

  after_create :send_notification

  def send_notification
    NewPostService.call()
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/notification.rb
class Notification < ApplicationRecord

  validates :email, presence: true, format: { 
    with: URI::MailTo::EMAIL_REGEXP,
    message: 'Only valid emails allowed'
  } 
  
  after_create :send_notification

  def send_notification
    SignUpService.call(notification: self)
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  layout "admin"
  http_basic_authenticate_with name: ENV.fetch("ADMIN_NAME"), password: ENV.fetch("ADMIN_PASSWORD")
 end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :get_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render "new"
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy

    redirect_to admin_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def get_article
    @article = Article.find(params[:id])
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "password",
  only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)

    if @notification.save
      flash[:success] = "Success!"
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def notification_params
    params.require(:notification).permit(:email)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/show.html.erb
<div class="c-about">
    <div class="c-about__title">
        <h1> ABOUT ME </h1>
    </div>
    <div class="c-about__image">
      <%= image_tag("me") %>
    </div>
    <div class="c-about__content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis turpis et ligula porttitor, vel molestie sapien rutrum. Vestibulum tempor ornare lacinia. Nulla a ante lectus. Duis tempor efficitur tortor, eu congue nisi molestie porttitor. Phasellus vitae est mauris. Integer gravida, velit in vestibulum sagittis, erat metus fermentum augue, eget consectetur leo lacus nec ligula. Proin blandit mauris eget urna molestie pellentesque. Donec rutrum, odio eget ullamcorper egestas, ligula purus interdum odio, id sagittis velit felis vitae lectus. Curabitur tristique nec libero eu sodales. Etiam congue ut nunc in gravida.</p>

<p>Vestibulum et est augue. Duis a urna maximus, vestibulum diam ut, aliquam nunc. Nam sed enim maximus, pharetra odio at, bibendum arcu. Donec nec dolor sapien. Aenean eu cursus diam, vel laoreet lectus. Morbi pharetra diam augue, non consectetur tellus feugiat ut. Nunc ornare fringilla ligula vitae mattis. Nunc euismod lobortis felis vel porttitor.</p>

<p>Vivamus sollicitudin nulla sit amet lectus mollis consectetur vel nec quam. Nunc vel tempus lectus. Aenean nec purus et mauris rutrum auctor dictum quis urna. Cras sit amet mattis augue. Integer sit amet ipsum sollicitudin, blandit ex nec, finibus nisl. Donec ultricies libero tellus, ornare ultricies lacus vulputate quis. Duis a nibh fermentum eros dignissim pharetra quis non sem. Morbi eu leo et lorem rhoncus fermentum. Etiam suscipit lobortis neque, et iaculis purus facilisis ut. Etiam vehicula ac augue eget accumsan. Aenean dapibus neque lectus, in maximus nulla accumsan eu. In hac habitasse platea dictumst.</p>

<p>Fusce quis risus mi. Etiam id ornare nibh. Nunc scelerisque nisi vel porta lacinia. Phasellus tristique tortor urna, tincidunt fermentum ligula semper eu. Praesent bibendum magna ligula. Duis ultrices sapien et massa finibus pretium. Vivamus leo libero, cursus maximus sollicitudin vitae, feugiat nec odio. Pellentesque sodales eleifend leo, in ultrices ante vestibulum in. Nullam nec lobortis magna. Duis lobortis risus vitae turpis interdum facilisis. Proin et leo mattis, tempus quam in, ullamcorper sem. Donec ornare enim at dapibus sodales. Quisque lobortis eget ante quis hendrerit. Morbi posuere ante eget gravida viverra. Nunc luctus lacus ac pharetra finibus. Mauris dapibus sollicitudin feugiat.</p>

<p>Integer ultrices odio eget odio pulvinar accumsan. Maecenas id scelerisque dui, sit amet efficitur mi. Sed hendrerit vitae purus id posuere. In suscipit maximus commodo. Cras porta, nisi nec venenatis sagittis, dolor justo porta erat, a bibendum nibh ligula et orci. In faucibus turpis id quam congue hendrerit. Sed sollicitudin at dolor ac volutpat. Curabitur sit amet tincidunt turpis, sed aliquam nisl. Nulla dui tortor, laoreet quis ex non, porta bibendum urna. Quisque purus augue, lobortis eget diam sed, tempor pharetra sem. Aliquam sit amet ultrices ex. Praesent lobortis semper eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet massa sed nisi condimentum dapibus.</p>
    </div>
</div>

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |form| %>
  <div class="form-group c-article__form">
    <%= render partial: "shared/error_messages", locals: { object: @article } %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :text %>
      <%= form.text_area :text, class: "form-control c-article__form-input-large" %>
    </div>

    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<div class="card">
  <h5 class="card-header">
    Edit Article
  </h5>
  <div class="c-article__edit">
    <%= render "form" %>

    <%= link_to "Back", admin_path %>
  </div>
</div>

app/views/admin/articles/index.html.erb
<div class="c-admin__articles  border  rounded">
  <h1>Articles</h1>
  <%= link_to "New article", new_admin_article_path, class: "btn btn-primary c-admin__button" %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Text</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text.truncate_words(15) %></td>
        <td><%= link_to "Show", admin_article_path(article), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_admin_article_path(article), class: "btn btn-primary" %>
        <%= link_to "Destroy", admin_article_path(article),
                method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render "form" %>

<%= link_to "Back", admin_articles_path %>

app/views/admin/articles/show.html.erb
<div class="card">
  <h5 class="card-header">
    <%= @article.title %>
  </h5>
  <div class="card-body">
    <p class="card-text">
      <%= simple_format @article.text %>
    </p>
    <%= link_to "Edit", edit_admin_article_path(@article) %> |
    <%= link_to "Back", admin_path %>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<div class="c-admin__articles  border  rounded">
  <h1>Articles</h1>
  <%= link_to "New article", new_admin_article_path, class: "btn btn-primary c-admin__button" %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Text</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text.truncate_words(15) %></td>
        <td><%= link_to "Show", admin_article_path(article), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_admin_article_path(article), class: "btn btn-primary" %>
        <%= link_to "Destroy", admin_article_path(article),
                method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="c-article">
    <div class="c-article__content">
      <div class="c-article__date">
        <%= article.created_at.to_s(:long) %>
      </div>
      <div class="c-article__image" align="center">
        <div class="o-container__article-hero">
          <%= image_tag("article_hero", class: "c-article__hero-image") %>
        </div>
      </div>
      <div class="c-article__title">
        <h1>
          <%= article.title %>
        </h1>
      </div>
      <div class="c-article__text">
        <p>
          <%= article.text.truncate(50, omission: '... (continued)') %>
        </p>
      </div>
      <div class="c-article__link">
        <%= link_to "READ ARTICLE", article_path(article) %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="c-article">
  <h1 class="c-article__title">
    <%= @article.title %>
  </h1>
  <div class="c-article__text">
    <p>
      <%= simple_format @article.text %>
    </p>
  </div>
  <%= link_to "Back", articles_path %> >
</div>
<div class="c-article__disqus" id="disqus_thread"></div>
<script>
(function() { // DON"T EDIT BELOW THIS LINE
var d = document, s = d.createElement("script");
s.src = "https://onsmith.disqus.com/embed.js";
s.setAttribute("data-timestamp", +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to "Destroy Comment", [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
<div class="c-comments__form">
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter, class: "c-comments__form-input" %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body, class: "c-comments__form-body" %>
    </p>
    <p>
      <%= form.submit class: "c-comments__form-submit" %>
    </p>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    "admin/application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
  <div class ="o-container">
    <div class="c-admin">
      <div class="c-admin__nav">
        <%= image_tag("os") %>
        <a class="navbar-brand" href="/">ADMIN PANEL</a>
        <li><%= link_to "Home", root_path %></li>
      </div>
      <div class="c-admin__content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Owen Smooth Wuk Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class ="o-container">
      <div class="o-container__nav">
        <input type="checkbox" id="burger-menu" class="c-navigation__checkbox" />
        <label for="burger-menu" class="c-navigation__hamburger">
          Menu
        </label>
        <nav class="c-navigation">
          <div class="c-navigation__logo">
            <a href="https://github.com/owensmooth">
              <%= image_tag("github")%>
            </a>
            <a href="https://www.linkedin.com/in/owen-smith-7ba94415b/">
              <%= image_tag("linkedin") %>
            </a>
          </div>
          <div class="c-navigation__links">
            <ul class="c-navigation__links-list">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", static_pages_about_path %></li>
              <li><%= link_to "Articles", articles_path %></li>
              <li><%= link_to "Login", admin_path %></li>
            </ul>
          </div>
        </nav>
      </div>
      <div class="o-container__header">
        <div class="c-header__text">
          <h1>owen smoov</h1>
          <h2>dev blog</h2>
        </div>
      </div>
      <div class="o-container__content">
        <div class="c-content">
          <div class="c-content__body">
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render partial: "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/notification_mailer.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
      body {text-align: center; background-color: #F2F2F2; font-family: "Roboto";}
      body h1 {text-transform: uppercase;}
      .c-header__text {padding: 10px; text-align: center;}
      .c-header__text h1 {color: #474747; font-size: 64px; font-weight: 500; padding: 0; margin: 0;}
      .c-header__text h2 {color: #ABABAB; font-size: 40px; font-weight: 500; padding: 0; margin: 0;}
      .o-container__header {height: 150px; background-color: white;}
    </style>
  </head>
   <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/new.html.erb
 <%= form_for @notification do |form| %>
  <div class="c-notification__errors">
    <%= render "shared/error_messages", object: @notification %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="o-container__footer">
  <div class="c-footer">
    <div class="c-footer__form">
      <h3 class="c-footer__form-header">Sign up for email notifications</h3>
      <%= form_for @notification ||= Notification.new do |form| %>
        <div class="c-footer__form-notification-input">
          <span>
            <%= form.text_field :email, placeholder: "Enter email", class: "c-footer__form-input" %>
          </span>
        </div>
        <div class="c-footer__form-notification-submit">
          <span>
            <%= form.submit "",  class: "c-footer__form-submit" %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="c-about">
    <div class="c-about__title">
        <h1> ABOUT ME </h1>
    </div>
    <div class="c-about__image">
      <%= image_tag("me") %>
    </div>
    <div class="c-about__content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis turpis et ligula porttitor, vel molestie sapien rutrum. Vestibulum tempor ornare lacinia. Nulla a ante lectus. Duis tempor efficitur tortor, eu congue nisi molestie porttitor. Phasellus vitae est mauris. Integer gravida, velit in vestibulum sagittis, erat metus fermentum augue, eget consectetur leo lacus nec ligula. Proin blandit mauris eget urna molestie pellentesque. Donec rutrum, odio eget ullamcorper egestas, ligula purus interdum odio, id sagittis velit felis vitae lectus. Curabitur tristique nec libero eu sodales. Etiam congue ut nunc in gravida.</p>

<p>Vestibulum et est augue. Duis a urna maximus, vestibulum diam ut, aliquam nunc. Nam sed enim maximus, pharetra odio at, bibendum arcu. Donec nec dolor sapien. Aenean eu cursus diam, vel laoreet lectus. Morbi pharetra diam augue, non consectetur tellus feugiat ut. Nunc ornare fringilla ligula vitae mattis. Nunc euismod lobortis felis vel porttitor.</p>

<p>Vivamus sollicitudin nulla sit amet lectus mollis consectetur vel nec quam. Nunc vel tempus lectus. Aenean nec purus et mauris rutrum auctor dictum quis urna. Cras sit amet mattis augue. Integer sit amet ipsum sollicitudin, blandit ex nec, finibus nisl. Donec ultricies libero tellus, ornare ultricies lacus vulputate quis. Duis a nibh fermentum eros dignissim pharetra quis non sem. Morbi eu leo et lorem rhoncus fermentum. Etiam suscipit lobortis neque, et iaculis purus facilisis ut. Etiam vehicula ac augue eget accumsan. Aenean dapibus neque lectus, in maximus nulla accumsan eu. In hac habitasse platea dictumst.</p>

<p>Fusce quis risus mi. Etiam id ornare nibh. Nunc scelerisque nisi vel porta lacinia. Phasellus tristique tortor urna, tincidunt fermentum ligula semper eu. Praesent bibendum magna ligula. Duis ultrices sapien et massa finibus pretium. Vivamus leo libero, cursus maximus sollicitudin vitae, feugiat nec odio. Pellentesque sodales eleifend leo, in ultrices ante vestibulum in. Nullam nec lobortis magna. Duis lobortis risus vitae turpis interdum facilisis. Proin et leo mattis, tempus quam in, ullamcorper sem. Donec ornare enim at dapibus sodales. Quisque lobortis eget ante quis hendrerit. Morbi posuere ante eget gravida viverra. Nunc luctus lacus ac pharetra finibus. Mauris dapibus sollicitudin feugiat.</p>

<p>Integer ultrices odio eget odio pulvinar accumsan. Maecenas id scelerisque dui, sit amet efficitur mi. Sed hendrerit vitae purus id posuere. In suscipit maximus commodo. Cras porta, nisi nec venenatis sagittis, dolor justo porta erat, a bibendum nibh ligula et orci. In faucibus turpis id quam congue hendrerit. Sed sollicitudin at dolor ac volutpat. Curabitur sit amet tincidunt turpis, sed aliquam nisl. Nulla dui tortor, laoreet quis ex non, porta bibendum urna. Quisque purus augue, lobortis eget diam sed, tempor pharetra sem. Aliquam sit amet ultrices ex. Praesent lobortis semper eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet massa sed nisi condimentum dapibus.</p>
    </div>
</div>